### ISSUE TITLE
Problem in making source file - ubuntu 

### ISSUE THREAD

**Issue by mhmorta** [gnebehay/CppMT#13]
Hi 
I downloaded source file and extracted it . i ran "cmake . " command and completed without any error . 

After running " make" i faced with this : 
[ 11%] Building CXX object CMakeFiles/cmt.dir/common.cpp.o
In file included from /home/mehrzad/AI/cv/CppMT-master/common.cpp:1:0:
/home/mehrzad/AI/cv/CppMT-master/common.h:16:12: error: ‘std::numeric_limits’ has not been declared
 using std::numeric_limits;
            ^
/home/mehrzad/AI/cv/CppMT-master/common.cpp: In function ‘float cmt::median(std::vector<float>&)’:
/home/mehrzad/AI/cv/CppMT-master/common.cpp:14:16: error: ‘numeric_limits’ was not declared in this scope
         return numeric_limits<float>::quiet_NaN();
                ^
/home/mehrzad/AI/cv/CppMT-master/common.cpp:14:31: error: expected primary-expression before ‘float’
         return numeric_limits<float>::quiet_NaN();
                               ^
/home/mehrzad/AI/cv/CppMT-master/common.cpp:14:31: error: expected ‘;’ before ‘float’
/home/mehrzad/AI/cv/CppMT-master/common.cpp:14:36: error: expected unqualified-id before ‘>’ token
         return numeric_limits<float>::quiet_NaN();
                                    ^
make[2]: **\* [CMakeFiles/cmt.dir/common.cpp.o] Error 1
make[1]: **\* [CMakeFiles/cmt.dir/all] Error 2
make: **\* [all] Error 2

What should i do ?

**Comment by gnebehay** [comment]
Can you try to follow this suggestion http://stackoverflow.com/questions/4798936/linux-g-numeric-limits-was-not-declared-in-this-scope-no-matching-function and include <limits> ?

**Comment by gnebehay** [comment]
Include limits (not able to type angular brackets here)

**Comment by mhmorta** [comment]
Thanks , i included it and it solved 
but in next step it stuck's in gui.cpp : 
[ 11%] Building CXX object CMakeFiles/cmt.dir/gui.cpp.o
/home/mehrzad/AI/cv/CppMT-master/gui.cpp: In function ‘void screenLog(cv::Mat, std::string)’:
/home/mehrzad/AI/cv/CppMT-master/gui.cpp:17:22: error: ‘getTextSize’ is not a member of ‘cv’
     Size text_size = cv::getTextSize(text, font, font_scale, thickness, &baseline);
                      ^
/home/mehrzad/AI/cv/CppMT-master/gui.cpp:28:59: error: ‘rectangle’ was not declared in this scope
     rectangle(im_draw, bl_rect, tr_rect, Scalar(0,0,0), -1);
                                                           ^
/home/mehrzad/AI/cv/CppMT-master/gui.cpp:30:74: error: ‘putText’ was not declared in this scope
     putText(im_draw, text, bl_text, font, font_scale, Scalar(255,255,255));
                                                                          ^
/home/mehrzad/AI/cv/CppMT-master/gui.cpp: In function ‘void onMouse(int, int, int, int, void_)’:
/home/mehrzad/AI/cv/CppMT-master/gui.cpp:62:60: error: ‘rectangle’ was not declared in this scope
         rectangle(im_draw, tl, Point(x, y), Scalar(255,0,0));
                                                            ^
make[2]: *_\* [CMakeFiles/cmt.dir/gui.cpp.o] Error 1
make[1]: **\* [CMakeFiles/cmt.dir/all] Error 2
make: **\* [all] Error 2

the point is i have openvc 3.0.0 and saw in your project description "OpenCV (>= 2.4.8, < 3)"
so i seem's  this is the problem ...

**Comment by gnebehay** [comment]
This was fixed with b1f78b0d5c8ca0e610b70273934ac259dbc13e0b
