### ISSUE TITLE
very poor tracking performance

### ISSUE THREAD

**Issue by ahundt** [gnebehay/CppMT#36]
I tried tracking simple objects I was holding in my hand using the macbook pro's isight camera, and performance seemed to be very poor. Objects would be completely lost within a few seconds even if I don't move or change the orientation much (including when orientation changes are enabled). Perhaps I'm using it wrong or only a certain type of use case is supported?

**Comment by cromwellunipro1** [comment]
That sounds puzzling as the tracker, from my experience is the best tracker I have tested. Maybe lighting or other issues may be responsible. Have had situations when using it for FPV, the tracking cut out instanting because, I believe from loss of frame because of the radio transmission noise. Try other cameras.

**Comment by p01aris** [comment]
if your computer is not powerful, it maybe lost a lots of video frame. That
may affect the tracking performance

On Fri, Jan 29, 2016 at 1:56 PM, cinspired notifications@github.com wrote:

> That sounds puzzling as the tracker, from my experience is the best
> tracker I have tested. Maybe lighting or other issues may be responsible.
> Have had situations when using it for FPV, the tracking cut out instanting
> because, I believe from loss of frame because of the radio transmission
> noise. Try other cameras.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gnebehay/CppMT/issues/36#issuecomment-176912583.

## 

Zheng Lu

Jilin University.

2699 Qianjin St

Changchun,Jilin,R.P.China,130012

Email: polaris.varlin@gmail.com

ph: +86-15643110346

---

The information contained in this e-mail, including any attachment (s), is
intended solely for use by the named addressee (s). If you are not the
intended recipient, or a person designated as responsible for delivering
such messages to the intended recipient, you are not authorized to
disclose, copy, distribute or retain this message, in whole or in part,
without written authorization from Jilin University.  This e-mail may
contain proprietary, confidential or privileged information.  If you have
received this message in error, please notify the sender immediately.  This
notice is included in all e-mail messages leaving Jilin university.  Thank
you for your cooperation.

**Comment by ahundt** [comment]
My computer is a 2014 15" MacBook Pro with an Intel Core i7, so I don't believe the issue is my computer being slow. 

I made sure to pull the latest version and compile in release mode. I don't know what changed but things seem substantially better.

**Comment by cjl10023** [comment]
Which OpenCV and compiler version are you using?

**Comment by ahundt** [comment]
```
homebrew/science/opencv: stable 2.4.12 (bottled), HEAD
Open source computer vision library
http://opencv.org/
/usr/local/Cellar/opencv/2.4.12_2 (231 files, 35.8M) *
  Built from source with: --with-qt --with-tbb --without-numpy
From: https://github.com/Homebrew/homebrew-science/blob/master/opencv.rb
==> Dependencies
Build: cmake ✘, pkg-config ✔
Required: jpeg ✔, libpng ✘, libtiff ✔
Recommended: eigen ✔, openexr ✔, homebrew/python/numpy ✔
Optional: gstreamer ✔, jasper ✘, libdc1394 ✔, openni ✔, qt ✔, tbb ✔, vtk ✔, ffmpeg ✔
```

```
± c++ --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```

Note this still isn't 100% ideal performance, just acceptable.
