### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by endotronic** [gnebehay/CppMT#37]
I cloned the repo, used cmake, and built with default and "release" configuration on a one-year-old Macbook Pro running OS X. It takes roughly 5 seconds to process a frame, which was not the performance I was expecting. I didn't change anything or provide any arguments to cmt. Is it possible to achieve nearly realtime performance? I didn't look at your implementation of optical flow, but I have previously found Lucas-Kanade to be very performant on the same machine.

**Comment by ahundt** [comment]
I've been able to duplicate this problem

**Comment by ahundt** [comment]
I made sure I was up to date and built in release mode and the performance was much better. I'm not sure what the cause was/is and if it will occur again.

**Comment by endotronic** [comment]
@ahundt Can you share the command you used to build? Did it seem to run in realtime? I imagine I used "cmake --build . --config Release" to build, but I don't remember exactly.

**Comment by ahundt** [comment]
I just went into ccmake . and made sure it was set to "Release". It does drop quite a few frames but that seems to happen with other software as well. I think it is because of the iSight camera I was trying it with. I may try other devices in the future but don't have anything to report now. 

Also, be sure that all dependencies are compiled in release. I'm sorry I don't have a more useful answer at the moment!

**Comment by endotronic** [comment]
No problem, and thanks for responding anyway! I was hoping to use CppMT for tracking in realtime on an iPhone, but it sounds like it might not perform well enough anyway. I implemented a similar sort of thing with 60 points and OpenCV's implementation of the Lucas-Kanade algorithm. With that, I'm able to achieve 20 FPS or better on iPhone 5S and newer. My technique is not as sophisticated, but it works well enough for what I need.

**Comment by ahundt** [comment]
I also posted some details about my configuration in https://github.com/gnebehay/CppMT/issues/36

**Comment by endotronic** [comment]
Oh excellent, I didn't see #36 when I opened this issue. I'll go ahead and close this one since it's a duplicate. Thanks again, @ahundt.
