### ISSUE TITLE
Missing trax.h file 

### ISSUE THREAD

**Issue by lethanhtoan2004** [gnebehay/CppMT#6]
Dear Mr Gnebehay, 
I downloaded the entire CppMT folder. However, running with Microsoft Visual studio, It is giving error missing trax.h file. Could you please check again if trax.h is truly missing on GitHub or the file could be excluded. Thank you very much.

**Comment by gnebehay** [comment]
Did you use cmake for creating the visual studio project file?

**Comment by gnebehay** [comment]
It appears that you are trying to compile the trax client, which is not necessary for using cmt.

**Comment by lethanhtoan2004** [comment]
Dear Mr Gnebehay, 
After successfully using CMake to create a visual studio project, i have run the project in debug mode. and got plenty of errors like below. Could you please suggest solution for the issue? I am C++ beginner and just want to run the program first and then later will read the program to understand further. Thank you very much. 

Error   1893    error C2133: 'S' : unknown size C:\Users\toan\Documents\Visual Studio 2010\Projects\CppMT-master\Consensus.cpp  153
Error   3383    error C2065: 'idx' : undeclared identifier  C:\Users\toan\Documents\Visual Studio 2010\Projects\CppMT-master\fastcluster\fastcluster.cpp    540
Error   363 error C2133: 'T' : unknown size C:\Users\toan\Documents\Visual Studio 2010\Projects\CppMT-master\Consensus.cpp  184

**Comment by lethanhtoan2004** [comment]
I was able to debug with a simple modification to make the program running by a simple change to clear the error. Thank you very much

 t_index N = points.size(); 
int S[2_N-1];
change to
int_ S = new int[2*N-1];
