### ISSUE TITLE
Errors in consensus.cpp

### ISSUE THREAD

**Issue by adam-szczombrowski** [gnebehay/CppMT#7]
Dear Mr. gnebehay,

I've compiled your code and I get following errors in consensus.cpp:

Error 1163 error C2057: expected constant expression    C:\Nerdzenie\CppMT-master\CppMT-master\Consensus.cpp    154
Error 1166 error C2057: expected constant expression    C:\Nerdzenie\CppMT-master\CppMT-master\Consensus.cpp    180
Error 1165 error C2133: 'S' : unknown size  C:\Nerdzenie\CppMT-master\CppMT-master\Consensus.cpp    154
Error 1168 error C2133: 'T' : unknown size  C:\Nerdzenie\CppMT-master\CppMT-master\Consensus.cpp    180
Error 1164 error C2466: cannot allocate an array of constant size 0 C:\Nerdzenie\CppMT-master\CppMT-master\Consensus.cpp    154
Error 1167 error C2466: cannot allocate an array of constant size 0 C:\Nerdzenie\CppMT-master\CppMT-master\Consensus.cpp    180

Do you have any idea how can I solve this?

**Comment by josephmisiti** [comment]
Have a look at this:

http://stackoverflow.com/a/7303774/323578

It looks like you are probably using a g++ compiler that does not support C99 or you are no passing the flag properly. I am currently running `g++ (GCC) 4.9.2 20141029 (prerelease)` and the project compiled fine.

**Comment by gnebehay** [comment]
These errors stem from my usage of variable length arrays which as I had to learn are not part of the C++ standard. It probably was a bad idea anyway to put so much stuff on the stack. I pushed a commit recently that changed this to heap allocation.
