### ISSUE TITLE
Errors in while building cmt

### ISSUE THREAD

**Issue by Marcuslief** [gnebehay/CppMT#8]
Hi , I am getting these errors while building CMT solution in Visual Studio 2013.

Error   1   error LNK2019: unresolved external symbol __imp_getopt_long_a referenced in function main   C:\Users\Administrator\Desktop\CPPMT\cmt\main.obj   cmt
Error   2   error LNK2001: unresolved external symbol __imp_optind  C:\Users\Administrator\Desktop\CPPMT\cmt\main.obj   cmt
Error   3   error LNK2001: unresolved external symbol __imp_optarg_a    C:\Users\Administrator\Desktop\CPPMT\cmt\main.obj   cmt
Error   4   error LNK1120: 3 unresolved externals   C:\Users\Administrator\Desktop\CPPMT\cmt\Debug\cmt.exe  cmt

I think these errors show up due to errors in the code. Please help me.

**Comment by gnebehay** [comment]
I just pushed a commit that fixes this issue. Please try again.
